# Generated by Django 6.0.6 on 2026-06-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loterias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="prize_tiers",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
